Add mpirun & mpiexec as wrappers for target's

diff --git a/src/interface/interface_utils/bin/mpirun b/src/interface/interface_utils/bin/mpirun
--- a/src/interface/interface_utils/bin/mpirun
+++ b/src/interface/interface_utils/bin/mpirun
@@ -1,10 +1,51 @@
 #!/bin/bash
 
-cat << EOF
-= INFO =
-WI4MPI doesn't provide its own launcher, you need to use another MPI launcher with wi4mpi executable.
-= EXAMPLES =
-OpenMPI: \${OPENMPI_ROOT}/bin/mpirun wi4mpi -t openmpi ./exe
-Bridge: ccc_mprun wi4mpi -t openmpi ./exe
-MPC: wi4mpi -t mpc mpcrun ./exe
-EOF
+############################# Wi4MPI License ###########################
+# `04/04/2016`                                                         #
+# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
+#                                                                      #
+# IDDN.FR.001.210022.000.S.P.2014.000.10800                            #
+# This file is part of the Wi4MPI library.                             #
+#                                                                      #
+# This software is governed by the CeCILL-C license under French law   #
+# and abiding by the rules of distribution of free software. You can   #
+# use, modify and/ or redistribute the software under the terms of     #
+# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
+# following URL http://www.cecill.info.                                #
+#                                                                      #
+# The fact that you are presently reading this means that you have     #
+# had knowledge of the CeCILL-C license and that you accept its        #
+# terms.                                                               #
+#                                                                      #
+# Authors:                                                             #
+#   - Delforge Tony <tony.delforge.tgcc@cea.fr>                        #
+#   - Ducrot Vincent <vincent.ducrot.tgcc@cea.fr>                      #
+#   - Adrien Cotte <adrien.cotte.tgcc@cea.fr>                          #
+#                                                                      #
+########################################################################
+
+WI4MPI_GCONFIG=$( readlink -f $(dirname $0)/../etc/wi4mpi.cfg )
+WI4MPI_UCONFIG="~/.wi4mpi.cfg"
+
+progname=$(basename $0)
+
+[[ -z $WI4MPI_ROOT ]] && (>&2 echo "$progname error: please set WI4MPI_ROOT") && exit 1
+[[ -z $WI4MPI_TO ]] && (>&2 echo "$progname error: please set WI4MPI_TO") && exit 1
+[[ -f $WI4MPI_GCONFIG ]] && source $WI4MPI_GCONFIG
+[[ -f $WI4MPI_UCONFIG ]] && source $WI4MPI_UCONFIG
+
+MPIRUN_OPT=()
+while [[ $# -gt 1 ]]; do
+    MPIRUN_OPT="$MPIRUN_OPT $1"
+    shift
+done
+
+if [[ ${WI4MPI_TO,,} = *"openmpi"* ]]; then
+    echo "$OPENMPI_DEFAULT_ROOT/bin/mpirun $MPIRUN_OPT wi4mpi -t openmpi $@"
+    $OPENMPI_DEFAULT_ROOT/bin/mpirun $MPIRUN_OPT wi4mpi -t openmpi $@
+elif [[ ${WI4MPI_TO,,} == *"intelmpi"* ]]; then
+    echo "$INTELMPI_DEFAULT_ROOT/bin64/mpirun $MPIRUN_OPT wi4mpi -t intelmpi $@"
+    $INTELMPI_DEFAULT_ROOT/bin64/mpirun $MPIRUN_OPT wi4mpi -t intelmpi $@
+else
+    (>&2 echo "$progname error: wi4mpirun not implemented for $WI4MPI_TO") && exit 1
+fi
diff --git a/src/preload/bin/wi4mpi b/src/preload/bin/wi4mpi
--- a/src/preload/bin/wi4mpi
+++ b/src/preload/bin/wi4mpi
@@ -130,8 +130,7 @@ if [[ -z $FROM ]]; then
         ;;
       *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
     esac
-    WI4MPI_FROM="INTERFACE"
-    WI4MPI_TO=${TARGET_FAMILY}
+    [[ -z $WI4MPI_TO ]] && (>&2 echo "$progname error: please set WI4MPI_TO") && exit 1
     WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
     WI4MPI_MPIIO_LIB="${WI4MPI_MPIIO_LIB:-$WI4MPI_RUN_MPI_C_LIB}"
     LD_LIBRARY_PATH=${WI4MPI_INTERFACE}:$LD_LIBRARY_PATH
@@ -147,8 +146,6 @@ if [[ -z $FROM ]]; then
     [[ ! -e ${WI4MPI_RUN_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
     [[ ! -e ${WI4MPI_MPIIO_LIB} ]] && { echo "Error: could not find the MPI-IO target mpi library." >&2 ; exit 1; }
     export LD_LIBRARY_PATH
-    export WI4MPI_FROM
-    export WI4MPI_TO
     export WI4MPI_WRAPPER_LIB
     export WI4MPI_RUN_MPI_C_LIB
     export WI4MPI_RUN_MPI_F_LIB
@@ -183,14 +180,12 @@ else
         ;;
       *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
     esac
-    WI4MPI_FROM=$FROM_FAMILY
-    WI4MPI_TO=$TARGET_FAMILY
+    [[ -z $WI4MPI_FROM ]] && (>&2 echo "$progname error: please set WI4MPI_FROM") && exit 1
+    [[ -z $WI4MPI_TO ]] && (>&2 echo "$progname error: please set WI4MPI_TO") && exit 1
     libwi4mpi="${WI4MPI_LIBEXEC}/libwi4mpi_${FROM_FAMILY}_${TARGET_FAMILY}.so"
     [[ ! -e $libwi4mpi ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; }
     [[ ! -e ${WI4MPI_RUN_MPI_C_LIB} ]] && { echo "Error: could not find the C target mpi library." >&2 ; exit 1; }
     [[ ! -e ${WI4MPI_RUN_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
-    export WI4MPI_FROM
-    export WI4MPI_TO
     export WI4MPI_RUN_MPI_F_LIB
     export WI4MPI_RUN_MPI_C_LIB
     export LD_PRELOAD="${LD_PRELOAD:+${LD_PRELOAD} }${libwi4mpi} ${WI4MPI_RUN_MPI_F_LIB} ${WI4MPI_RUN_MPI_C_LIB}"
