Add WI4MPI_RUN_MPIIO_C_LIB and WI4MPI_RUN_MPIIO_F_LIB to choose the right lib_handle_io

diff --git a/src/preload/bin/wi4mpi b/src/preload/bin/wi4mpi
--- a/src/preload/bin/wi4mpi
+++ b/src/preload/bin/wi4mpi
@@ -101,25 +101,32 @@ if [[ -z $FROM ]]; then
         WI4MPI_FAMILY=${WI4MPI_OMPI}
         WI4MPI_RUN_MPI_C_LIB="$OPENMPI_ROOT/lib/libmpi.so"
         WI4MPI_RUN_MPI_F_LIB="$OPENMPI_ROOT/lib/libmpi_mpifh.so"
+        WI4MPI_RUN_MPIIO_C_LIB="$OPENMPI_ROOT/lib/libmpi.so"
+        WI4MPI_RUN_MPIIO_F_LIB="$OPENMPI_ROOT/lib/libmpi_mpifh.so"
         ;;
       intelmpi)
         TARGET_FAMILY="INTEL"
         WI4MPI_FAMILY=${WI4MPI_INTEL}
         WI4MPI_RUN_MPI_C_LIB="$INTELMPI_ROOT/lib64/libmpi.so"
         WI4MPI_RUN_MPI_F_LIB="$INTELMPI_ROOT/lib64/libmpifort.so"
+        WI4MPI_RUN_MPIIO_C_LIB="$INTELMPI_ROOT/lib64/libmpi.so"
+        WI4MPI_RUN_MPIIO_F_LIB="$INTELMPI_ROOT/lib64/libmpifort.so"
         ;;
       mpich)
         TARGET_FAMILY="MPICH"
         WI4MPI_FAMILY=${WI4MPI_MPICH}
         WI4MPI_RUN_MPI_C_LIB="$MPICH_ROOT/lib/libmpi.so"
         WI4MPI_RUN_MPI_F_LIB="$MPICH_ROOT/lib/libmpifort.so"
+        WI4MPI_RUN_MPIIO_C_LIB="$MPICH_ROOT/lib/libmpi.so"
+        WI4MPI_RUN_MPIIO_F_LIB="$MPICH_ROOT/lib/libmpifort.so"
         ;;
       mpc)
         TARGET_FAMILY="MPC"
         WI4MPI_FAMILY=${WI4MPI_MPC}
         WI4MPI_RUN_MPI_C_LIB="$MPC_ROOT/lib/libmpc_framework.so"
         WI4MPI_RUN_MPI_F_LIB="$MPC_ROOT/lib/libmpc_frameworkf.so"
-        WI4MPI_MPIIO_LIB="$MPC_ROOT/lib/libromio.so"
+        WI4MPI_RUN_MPIIO_C_LIB="$MPC_ROOT/lib/libromio.so"
+        WI4MPI_RUN_MPIIO_F_LIB="$MPC_ROOT/lib/libromio.so"
         WI4MPI_MPC_HOOK_MAIN_LIB="$MPC_ROOT/lib/libmpc_hookmain.so"
         WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
         LD_PRELOAD="${WI4MPI_WRAPPER_LIB} ${WI4MPI_INTERFACE}/libmpi.so ${WI4MPI_RUN_MPI_C_LIB} ${WI4MPI_MPC_HOOK_MAIN_LIB}"
@@ -133,26 +140,29 @@ if [[ -z $FROM ]]; then
     WI4MPI_FROM="INTERFACE"
     WI4MPI_TO=$TARGET_FAMILY
     WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
-    WI4MPI_MPIIO_LIB="${WI4MPI_MPIIO_LIB:-$WI4MPI_RUN_MPI_C_LIB}"
     LD_LIBRARY_PATH=${WI4MPI_INTERFACE}:$LD_LIBRARY_PATH
     if [[ -n "$VERBOSE" ]]; then
-        echo ${WI4MPI_WRAPPER_LIB}
-        echo ${WI4MPI_RUN_MPI_C_LIB}
-        echo ${WI4MPI_RUN_MPI_F_LIB}
-        echo $LD_LIBRARY_PATH
-        echo $LD_PRELOAD
+        echo "export WI4MPI_WRAPPER_LIB=${WI4MPI_WRAPPER_LIB}"
+        echo "export WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB}"
+        echo "export WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB}"
+        echo "export WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB}"
+        echo "export WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB}"
+        echo "export LD_PRELOAD=\"${LD_PRELOAD}\""
+        echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
     fi
     [[ ! -e ${WI4MPI_WRAPPER_LIB} ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; }
     [[ ! -e ${WI4MPI_RUN_MPI_C_LIB} ]] && { echo "Error: could not find the C target mpi library." >&2 ; exit 1; }
     [[ ! -e ${WI4MPI_RUN_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
-    [[ ! -e ${WI4MPI_MPIIO_LIB} ]] && { echo "Error: could not find the MPI-IO target mpi library." >&2 ; exit 1; }
+    [[ ! -e ${WI4MPI_RUN_MPIIO_C_LIB} ]] && { echo "Error: could not find the C target mpi-io library." >&2 ; exit 1; }
+    [[ ! -e ${WI4MPI_RUN_MPIIO_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi-io library." >&2 ; exit 1; }
     export WI4MPI_FROM
     export WI4MPI_TO
     export LD_LIBRARY_PATH
     export WI4MPI_WRAPPER_LIB
     export WI4MPI_RUN_MPI_C_LIB
     export WI4MPI_RUN_MPI_F_LIB
-    export WI4MPI_MPIIO_LIB
+    export WI4MPI_RUN_MPIIO_C_LIB
+    export WI4MPI_RUN_MPIIO_F_LIB
 #PRELOAD
 else
     if [[ -n "$VERBOSE" ]]; then
@@ -170,16 +180,22 @@ else
         TARGET_FAMILY="OMPI"
         WI4MPI_RUN_MPI_C_LIB="$OPENMPI_ROOT/lib/libmpi.so"
         WI4MPI_RUN_MPI_F_LIB="$OPENMPI_ROOT/lib/libmpi_mpifh.so"
+        WI4MPI_RUN_MPIIO_C_LIB="$OPENMPI_ROOT/lib/libmpi.so"
+        WI4MPI_RUN_MPIIO_F_LIB="$OPENMPI_ROOT/lib/libmpi_mpifh.so"
         ;;
       intelmpi)
         TARGET_FAMILY="INTEL"
         WI4MPI_RUN_MPI_C_LIB="$INTELMPI_ROOT/lib64/libmpi.so"
         WI4MPI_RUN_MPI_F_LIB="$INTELMPI_ROOT/lib64/libmpifort.so"
+        WI4MPI_RUN_MPIIO_C_LIB="$INTELMPI_ROOT/lib64/libmpi.so"
+        WI4MPI_RUN_MPIIO_F_LIB="$INTELMPI_ROOT/lib64/libmpifort.so"
         ;;
       mpich)
         TARGET_FAMILY="MPICH"
         WI4MPI_RUN_MPI_C_LIB="$MPICH_ROOT/lib/libmpi.so"
         WI4MPI_RUN_MPI_F_LIB="$MPICH_ROOT/lib/libmpifort.so"
+        WI4MPI_RUN_MPIIO_C_LIB="$MPICH_ROOT/lib/libmpi.so"
+        WI4MPI_RUN_MPIIO_F_LIB="$MPICH_ROOT/lib/libmpifort.so"
         ;;
       *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
     esac
@@ -189,14 +205,20 @@ else
     [[ ! -e $libwi4mpi ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; }
     [[ ! -e ${WI4MPI_RUN_MPI_C_LIB} ]] && { echo "Error: could not find the C target mpi library." >&2 ; exit 1; }
     [[ ! -e ${WI4MPI_RUN_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
+    [[ ! -e ${WI4MPI_RUN_MPIIO_C_LIB} ]] && { echo "Error: could not find the C target mpi-io library." >&2 ; exit 1; }
+    [[ ! -e ${WI4MPI_RUN_MPIIO_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi-io library." >&2 ; exit 1; }
     export WI4MPI_FROM
     export WI4MPI_TO
     export WI4MPI_RUN_MPI_F_LIB
     export WI4MPI_RUN_MPI_C_LIB
+    export WI4MPI_RUN_MPIIO_C_LIB
+    export WI4MPI_RUN_MPIIO_F_LIB
     export LD_PRELOAD="${LD_PRELOAD:+${LD_PRELOAD} }${libwi4mpi} ${WI4MPI_RUN_MPI_F_LIB} ${WI4MPI_RUN_MPI_C_LIB}"
     if [[ -n "$VERBOSE" ]]; then
         echo "export WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB}"
         echo "export WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB}"
+        echo "export WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB}"
+        echo "export WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB}"
         echo "export LD_PRELOAD=\"${LD_PRELOAD}\""
     fi
     libfakedir_cxx="${WI4MPI_LIBEXEC}/fakelibCXX/"
