bin/wi4mpi: move LD_PRELOAD and MPC_HOOK_MAIN to MPC exclusive section

diff --git a/src/preload/bin/wi4mpi b/src/preload/bin/wi4mpi
--- a/src/preload/bin/wi4mpi
+++ b/src/preload/bin/wi4mpi
@@ -109,6 +109,12 @@ if [[ -z $FROM ]]; then
 		WI4MPI_RUN_MPI_C_LIB="$MPC_ROOT/lib/libmpc_framework.so"
 		WI4MPI_RUN_MPI_F_LIB="$MPC_ROOT/lib/libmpc_frameworkf.so"
         MPC_HOOK_MAIN_LIB="$MPC_ROOT/lib/libmpc_hookmain.so"
+	    WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
+        LD_PRELOAD="${WI4MPI_WRAPPER_LIB} ${WI4MPI_INTERFACE}/libmpi.so ${WI4MPI_RUN_MPI_C_LIB} ${MPC_HOOK_MAIN_LIB}"
+	    [[ -n "$VERBOSE" ]] && echo $MPC_HOOK_MAIN_LIB && echo $LD_PRELOAD
+	    [[ ! -e ${MPC_HOOK_MAIN_LIB} ]] && { echo "Error: could not find the HOOK_MAIN library for MPC support." >&2 ; exit 1; }
+        export MPC_HOOK_MAIN_LIB
+        export LD_PRELOAD
 		;;
   	  *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
 	esac
@@ -116,27 +122,22 @@ if [[ -z $FROM ]]; then
 	WI4MPI_TO=${TARGET_FAMILY}
 	WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
 	LD_LIBRARY_PATH=${WI4MPI_INTERFACE}:$LD_LIBRARY_PATH
-    LD_PRELOAD="${WI4MPI_WRAPPER_LIB} ${WI4MPI_INTERFACE}/libmpi.so ${WI4MPI_RUN_MPI_C_LIB} ${MPC_HOOK_MAIN_LIB}"
 	if [[ -n "$VERBOSE" ]]; then
 		echo ${WI4MPI_WRAPPER_LIB}
 		echo ${WI4MPI_RUN_MPI_C_LIB}
 		echo ${WI4MPI_RUN_MPI_F_LIB}
-        echo $MPC_HOOK_MAIN_LIB
 		echo $LD_LIBRARY_PATH
         echo $LD_PRELOAD
 	fi
 	[[ ! -e ${WI4MPI_WRAPPER_LIB} ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; } 
 	[[ ! -e ${WI4MPI_RUN_MPI_C_LIB} ]] && { echo "Error: could not find the C target mpi library." >&2 ; exit 1; }
 	[[ ! -e ${WI4MPI_RUN_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
-	[[ ! -e ${MPC_HOOK_MAIN_LIB} ]] && { echo "Error: could not find the HOOK_MAIN library for MPC support." >&2 ; exit 1; }
     export LD_LIBRARY_PATH
 	export WI4MPI_FROM
 	export WI4MPI_TO
 	export WI4MPI_WRAPPER_LIB
 	export WI4MPI_RUN_MPI_C_LIB
 	export WI4MPI_RUN_MPI_F_LIB
-    export MPC_HOOK_MAIN_LIB
-    export LD_PRELOAD
 #PRELOAD	
 else
 	if [[ -n "$VERBOSE" ]]; then
