factorize case $TARGET

diff --git a/src/preload/bin/wi4mpi b/src/preload/bin/wi4mpi
--- a/src/preload/bin/wi4mpi
+++ b/src/preload/bin/wi4mpi
@@ -54,6 +54,57 @@ EOF
 
 }
 
+wi4mpi_set_target_vars() {
+    local TARGET="$1"
+    local is_preload=$2
+    case $TARGET in
+      openmpi)
+        TARGET_FAMILY="OMPI"
+        [[ $is_preload -eq 0 ]] && WI4MPI_FAMILY=${WI4MPI_OMPI}
+        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$OPENMPI_ROOT/lib/libmpi.so"}
+        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$OPENMPI_ROOT/lib/libmpi_mpifh.so"}
+        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$OPENMPI_ROOT/lib/libmpi.so"}
+        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$OPENMPI_ROOT/lib/libmpi_mpifh.so"}
+        ;;
+      intelmpi)
+        TARGET_FAMILY="INTEL"
+        [[ $is_preload -eq 0 ]] && WI4MPI_FAMILY=${WI4MPI_INTEL}
+        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$INTELMPI_ROOT/lib64/libmpi.so"}
+        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$INTELMPI_ROOT/lib64/libmpifort.so"}
+        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$INTELMPI_ROOT/lib64/libmpi.so"}
+        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$INTELMPI_ROOT/lib64/libmpifort.so"}
+        ;;
+      mpich)
+        TARGET_FAMILY="MPICH"
+        [[ $is_preload -eq 0 ]] && WI4MPI_FAMILY=${WI4MPI_MPICH}
+        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$MPICH_ROOT/lib/libmpi.so"}
+        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$MPICH_ROOT/lib/libmpifort.so"}
+        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$MPICH_ROOT/lib/libmpi.so"}
+        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$MPICH_ROOT/lib/libmpifort.so"}
+        ;;
+      mpc)
+        if [[ $is_preload -eq 1 ]]; then
+            echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
+        fi
+        source $MPC_ROOT/../../mpcvars.sh
+        TARGET_FAMILY="MPC"
+        WI4MPI_FAMILY=${WI4MPI_MPC}
+        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$MPC_ROOT/lib/libmpc_framework.so"}
+        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$MPC_ROOT/lib/libmpc_frameworkf.so"}
+        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$MPC_ROOT/lib/libromio.so"}
+        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$MPC_ROOT/lib/libromio.so"}
+        WI4MPI_MPC_HOOK_MAIN_LIB="$MPC_ROOT/lib/libmpc_hookmain.so"
+        WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
+        LD_PRELOAD="${WI4MPI_WRAPPER_LIB} ${WI4MPI_INTERFACE}/libmpi.so ${WI4MPI_RUN_MPI_C_LIB} ${WI4MPI_MPC_HOOK_MAIN_LIB}"
+        [[ -n "$VERBOSE" ]] && echo $WI4MPI_MPC_HOOK_MAIN_LIB && echo $LD_PRELOAD
+        [[ ! -e ${WI4MPI_MPC_HOOK_MAIN_LIB} ]] && { echo "Error: could not find the HOOK_MAIN library for MPC support." >&2 ; exit 1; }
+        export WI4MPI_MPC_HOOK_MAIN_LIB
+        export LD_PRELOAD
+        ;;
+      *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
+    esac
+}
+
 VERBOSE=""
 WI4MPI_LIBEXEC=$( readlink -e $(dirname $0)/../libexec/wi4mpi )
 WI4MPI_INTEL=$( readlink -e $(dirname $0)/../lib_INTEL )
@@ -95,49 +146,7 @@ if [[ -z $FROM ]]; then
         echo "INTERFACE MODE"
     fi
     FROM_FAMILY="CCC"
-    case $TARGET in
-      openmpi)
-        TARGET_FAMILY="OMPI"
-        WI4MPI_FAMILY=${WI4MPI_OMPI}
-        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$OPENMPI_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$OPENMPI_ROOT/lib/libmpi_mpifh.so"}
-        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$OPENMPI_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$OPENMPI_ROOT/lib/libmpi_mpifh.so"}
-        ;;
-      intelmpi)
-        TARGET_FAMILY="INTEL"
-        WI4MPI_FAMILY=${WI4MPI_INTEL}
-        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$INTELMPI_ROOT/lib64/libmpi.so"}
-        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$INTELMPI_ROOT/lib64/libmpifort.so"}
-        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$INTELMPI_ROOT/lib64/libmpi.so"}
-        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$INTELMPI_ROOT/lib64/libmpifort.so"}
-        ;;
-      mpich)
-        TARGET_FAMILY="MPICH"
-        WI4MPI_FAMILY=${WI4MPI_MPICH}
-        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$MPICH_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$MPICH_ROOT/lib/libmpifort.so"}
-        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$MPICH_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$MPICH_ROOT/lib/libmpifort.so"}
-        ;;
-      mpc)
-        source $MPC_ROOT/../../mpcvars.sh
-        TARGET_FAMILY="MPC"
-        WI4MPI_FAMILY=${WI4MPI_MPC}
-        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$MPC_ROOT/lib/libmpc_framework.so"}
-        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$MPC_ROOT/lib/libmpc_frameworkf.so"}
-        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$MPC_ROOT/lib/libromio.so"}
-        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$MPC_ROOT/lib/libromio.so"}
-        WI4MPI_MPC_HOOK_MAIN_LIB="$MPC_ROOT/lib/libmpc_hookmain.so"
-        WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
-        LD_PRELOAD="${WI4MPI_WRAPPER_LIB} ${WI4MPI_INTERFACE}/libmpi.so ${WI4MPI_RUN_MPI_C_LIB} ${WI4MPI_MPC_HOOK_MAIN_LIB}"
-        [[ -n "$VERBOSE" ]] && echo $WI4MPI_MPC_HOOK_MAIN_LIB && echo $LD_PRELOAD
-        [[ ! -e ${WI4MPI_MPC_HOOK_MAIN_LIB} ]] && { echo "Error: could not find the HOOK_MAIN library for MPC support." >&2 ; exit 1; }
-        export WI4MPI_MPC_HOOK_MAIN_LIB
-        export LD_PRELOAD
-        ;;
-      *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
-    esac
+    wi4mpi_set_target_vars $TARGET 0
     WI4MPI_FROM="INTERFACE"
     WI4MPI_TO=$TARGET_FAMILY
     WI4MPI_WRAPPER_LIB="${WI4MPI_FAMILY}/libwi4mpi_${TARGET_FAMILY}.so"
@@ -179,30 +188,7 @@ else
     *) echo "Error: Unsupported Origin MPI stack." >&2 ; exit 1;
     esac
 
-    case $TARGET in
-      openmpi)
-        TARGET_FAMILY="OMPI"
-        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$OPENMPI_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$OPENMPI_ROOT/lib/libmpi_mpifh.so"}
-        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$OPENMPI_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$OPENMPI_ROOT/lib/libmpi_mpifh.so"}
-        ;;
-      intelmpi)
-        TARGET_FAMILY="INTEL"
-        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$INTELMPI_ROOT/lib64/libmpi.so"}
-        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$INTELMPI_ROOT/lib64/libmpifort.so"}
-        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$INTELMPI_ROOT/lib64/libmpi.so"}
-        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$INTELMPI_ROOT/lib64/libmpifort.so"}
-        ;;
-      mpich)
-        TARGET_FAMILY="MPICH"
-        WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB:-"$MPICH_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB:-"$MPICH_ROOT/lib/libmpifort.so"}
-        WI4MPI_RUN_MPIIO_C_LIB=${WI4MPI_RUN_MPIIO_C_LIB:-"$MPICH_ROOT/lib/libmpi.so"}
-        WI4MPI_RUN_MPIIO_F_LIB=${WI4MPI_RUN_MPIIO_F_LIB:-"$MPICH_ROOT/lib/libmpifort.so"}
-        ;;
-      *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
-    esac
+    wi4mpi_set_target_vars $TARGET 1
     WI4MPI_FROM=$FROM_FAMILY
     WI4MPI_TO=$TARGET_FAMILY
     libwi4mpi="${WI4MPI_LIBEXEC}/libwi4mpi_${FROM_FAMILY}_${TARGET_FAMILY}.so"
