version 3.1.4

diff --git a/src/preload/bin/wi4mpi b/src/preload/bin/wi4mpi
--- a/src/preload/bin/wi4mpi
+++ b/src/preload/bin/wi4mpi
@@ -23,8 +23,6 @@
 #                                                                      #
 ########################################################################
 
-
-# TODO: CXX language
 usage() {
 
     cat <<EOF
@@ -38,28 +36,26 @@ Option:
     -h           the help message
     -f FROM      the MPI implentation from which PROGRAM was compiled with
     -t TARGET    the MPI implentation to which PROGRAM will be run
-    -l LANGUAGE  the PROGRAM's Language
     -v           controls the verbosity
 
 Supported values:
-    FROM         bullxmpi,openmpi,intelmpi  (no default value)
-    TARGET       bullxmpi,openmpi,intelmpi  (no default value)
-    LANGUAGE     C,C++,FORTRAN              (default value is "C")
+    FROM         openmpi,intelmpi  (no default value)
+    TARGET       openmpi,intelmpi  (no default value)
 
 Influential environment variables:
 
   OPENMPI_ROOT
   INTELMPI_ROOT
-  BULLXMPI_ROOT
-  MPICH_ROOT  
 
 EOF
 
 }
 
 VERBOSE=""
-LANGUAGE="C"
 WI4MPI_LIBEXEC=$( readlink -e $(dirname $0)/../libexec/wi4mpi )
+WI4MPI_IMPI=$( readlink -e $(dirname $0)/../lib_IMPI )
+WI4MPI_OMPI=$( readlink -e $(dirname $0)/../lib_OMPI )
+WI4MPI_INTERFACE=$( readlink -e $(dirname $0)/../lib )
 WI4MPI_GCONFIG=$( readlink -f $(dirname $0)/../etc/wi4mpi.cfg )
 WI4MPI_UCONFIG="~/.wi4mpi.cfg"
 
@@ -68,8 +64,7 @@ WI4MPI_UCONFIG="~/.wi4mpi.cfg"
 
 OPENMPI_ROOT=${OPENMPI_ROOT:-${OPENMPI_DEFAULT_ROOT}}
 INTELMPI_ROOT=${INTELMPI_ROOT:-${INTELMPI_DEFAULT_ROOT}}
-BULLXMPI_ROOT=${BULLXMPI_ROOT:-${BULLXMPI_DEFAULT_ROOT}}
-MPICH_ROOT=${MPICH_ROOT:-${MPICH_DEFAULT_ROOT}}
+export WI4MPI_VERSION
 
 while getopts "f:t:hv" Option; do
   case "$Option" in
@@ -87,128 +82,94 @@ shift $(($OPTIND - 1))
 # No argument print help and exit
 [[ $# -eq 0 ]] && usage && exit 0 
 
-#echo 'FROM:'; echo $FROM
-#echo 'TARGET:'; echo $TARGET
-
-case $FROM in
-    bullxmpi) FROM_FAMILY="OMPI" ;;
+# INTERFACE MODE
+if [[ -z $FROM ]]; then
+	if [[ -n "$VERBOSE" ]]; then
+		echo "INTERFACE MODE"
+	fi
+	FROM_FAMILY="CCC"
+	case $TARGET in
+  	  openmpi)  
+		TARGET_FAMILY="OMPI"
+		WI4MPI_FAMILY=${WI4MPI_OMPI}
+		WI4MPI_RUN_MPI_C_LIB=$OPENMPI_ROOT/lib/libmpi.so 
+		WI4MPI_RUN_MPI_F_LIB=$OPENMPI_ROOT/lib/libmpi_mpifh.so
+		;;
+  	  intelmpi) 
+		TARGET_FAMILY="INTEL"
+		WI4MPI_FAMILY=${WI4MPI_IMPI}
+		WI4MPI_RUN_MPI_C_LIB=$INTELMPI_ROOT/lib64/libmpi.so
+		WI4MPI_RUN_MPI_F_LIB=$INTELMPI_ROOT/lib64/libmpifort.so
+		;;
+  	  *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
+	esac
+	WI4MPI_FROM="INTERFACE"
+	WI4MPI_TO=${TARGET_FAMILY}
+	WI4MPI_WRAPPER_LIB=${WI4MPI_FAMILY}/libwi4mpi_${FROM_FAMILY}_${TARGET_FAMILY}.so
+	export LD_LIBRARY_PATH=${WI4MPI_INTERFACE}:$LD_LIBRARY_PATH
+	if [[ -n "$VERBOSE" ]]; then
+		echo ${WI4MPI_WRAPPER_LIB}
+		echo ${WI4MPI_RUN_MPI_C_LIB}
+		echo ${WI4MPI_RUN_MPI_F_LIB}
+		echo $LD_LIBRARY_PATH
+	fi
+	[[ ! -f ${WI4MPI_WRAPPER_LIB} ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; } 
+	[[ ! -f ${WI4MPI_RUN_MPI_C_LIB} ]] && { echo "Error: could not find the C target mpi library." >&2 ; exit 1; }
+	[[ ! -f ${WI4MPI_RUN_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
+	export WI4MPI_FROM
+	export WI4MPI_TO
+	export WI4MPI_WRAPPER_LIB
+	export WI4MPI_RUN_MPI_C_LIB
+	export WI4MPI_RUN_MPI_F_LIB	
+#PRELOAD	
+else
+	if [[ -n "$VERBOSE" ]]; then
+		echo "PRELOAD MODE"
+	fi
+	case $FROM in
     openmpi)  FROM_FAMILY="OMPI" ;;
     intelmpi) FROM_FAMILY="INTEL" ;;
-    mpich)    FROM_FAMILY="INTEL" ;;
     *) echo "Error: Unsupported Origin MPI stack." >&2 ; exit 1;
-esac
+	esac
 
-case $TARGET in
-    bullxmpi) 
-	TARGET_FAMILY="OMPI" 
-	TRUE_MPI_LIB=$BULLXMPI_ROOT/lib/libmpi.so 
-	TRUE_MPI_F_LIB=$BULLXMPI_ROOT/lib/libmpi_f77.so
-	;;
-    openmpi)  
-	TARGET_FAMILY="OMPI" 
-	TRUE_MPI_LIB=$OPENMPI_ROOT/lib/libmpi.so 
-	TRUE_MPI_F_LIB=$OPENMPI_ROOT/lib/libmpi_mpifh.so
-	;;
-    intelmpi) 
-	TARGET_FAMILY="INTEL"
-	TRUE_MPI_LIB=$INTELMPI_ROOT/lib64/libmpi.so
-	TRUE_MPI_F_LIB=$INTELMPI_ROOT/lib64/libmpifort.so
-	;;
-    mpich)    
-	TARGET_FAMILY="INTEL"
-	TRUE_MPI_LIB=$MPICH_ROOT/lib64/libmpi.so 
-	TRUE_MPI_F_LIB=$MPICH_ROOT/lib64/libmpifort.so
-	;;
-    *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
-esac
+	case $TARGET in
+  	  openmpi)  
+		TARGET_FAMILY="OMPI" 
+		WI4MPI_RUN_MPI_C_LIB=$OPENMPI_ROOT/lib/libmpi.so 
+		WI4MPI_RUN_MPI_F_LIB=$OPENMPI_ROOT/lib/libmpi_mpifh.so
+		;;
+  	  intelmpi) 
+		TARGET_FAMILY="INTEL"
+		WI4MPI_RUN_MPI_C_LIB=$INTELMPI_ROOT/lib64/libmpi.so
+		WI4MPI_RUN_MPI_F_LIB=$INTELMPI_ROOT/lib64/libmpifort.so
+		;;
+  	  *) echo "Error: Unsupported Target MPI stack." >&2 ; exit 1;
+	esac
+	WI4MPI_FROM=$FROM_FAMILY
+	WI4MPI_TO=$TARGET_FAMILY
+	libwi4mpi=${WI4MPI_LIBEXEC}/libwi4mpi_${FROM_FAMILY}_${TARGET_FAMILY}.so
+	[[ ! -f $libwi4mpi ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; } 
+	[[ ! -f ${WI4MPI_RUN_MPI_C_LIB} ]] && { echo "Error: could not find the C target mpi library." >&2 ; exit 1; }
+	[[ ! -f ${WI4MPI_RUN_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
+	export WI4MPI_FROM
+	export WI4MPI_TO
+	export WI4MPI_RUN_MPI_F_LIB
+	export WI4MPI_RUN_MPI_C_LIB
+	export LD_PRELOAD="${LD_PRELOAD:+${LD_PRELOAD} }${libwi4mpi} ${WI4MPI_RUN_MPI_F_LIB} ${WI4MPI_RUN_MPI_C_LIB}"
+	if [[ -n "$VERBOSE" ]]; then
+	    echo "export WI4MPI_RUN_MPI_F_LIB=${WI4MPI_RUN_MPI_F_LIB}"
+	    echo "export WI4MPI_RUN_MPI_C_LIB=${WI4MPI_RUN_MPI_C_LIB}"
+	    echo "export LD_PRELOAD=\"${LD_PRELOAD}\""
+	fi
+	libfakedir_cxx=${WI4MPI_LIBEXEC}/fakelibCXX/
+	[[ ! -d $libfakedir_cxx ]] && { echo "Error: could not find the wrapper extra libdircxx." >&2 ; exit 1; } 
+	export LD_LIBRARY_PATH=${libfakedir_cxx}:$LD_LIBRARY_PATH
+	if [[ ${FROM_FAMILY} != ${TARGET_FAMILY} ]]; then
+	    libfakedir=${WI4MPI_LIBEXEC}/fakelib${FROM_FAMILY}/
+	    [[ ! -d $libfakedir ]] && { echo "Error: could not find the wrapper extra libdir." >&2 ; exit 1; } 
+	          export LD_LIBRARY_PATH=${libfakedir}:$LD_LIBRARY_PATH
+	fi
 
-
-echo "Wrapping the calls from $FROM to $TARGET ."
-libwi4mpi=${WI4MPI_LIBEXEC}/libwi4mpi_${FROM_FAMILY}_${TARGET_FAMILY}.so
-[[ ! -f $libwi4mpi ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; } 
-[[ ! -f ${TRUE_MPI_LIB} ]] && { echo "Error: could not find the C target mpi library." >&2 ; exit 1; }
-[[ ! -f ${TRUE_MPI_F_LIB} ]] && { echo "Error: could not find the FORTRAN target mpi library." >&2 ; exit 1; }
-
-export TRUE_MPI_F_LIB
-export TRUE_MPI_LIB
-export LD_PRELOAD="${LD_PRELOAD:+${LD_PRELOAD} }${libwi4mpi} ${TRUE_MPI_F_LIB} ${TRUE_MPI_LIB}"
-
-if [[ -n "$VERBOSE" ]]; then
-    echo "export TRUE_MPI_F_LIB=${TRUE_MPI_F_LIB}"
-    echo "export TRUE_MPI_LIB=${TRUE_MPI_LIB}"
-    echo "export LD_PRELOAD=\"${LD_PRELOAD}\""
 fi
 
-# replacing libs cxx link to the binary file by empty libs from fakelibCXX in order to avoid conflicts (segfault)
-libfakedir_cxx=${WI4MPI_LIBEXEC}/fakelibCXX/
-[[ ! -d $libfakedir_cxx ]] && { echo "Error: could not find the wrapper extra libdircxx." >&2 ; exit 1; } 
-export LD_LIBRARY_PATH=${libfakedir_cxx}:$LD_LIBRARY_PATH
-# replacing libs link to the binary file which are not defined by the target MPI lib by an empty library from fakelib_${FROM_FAMILY}
-if [[ ${FROM_FAMILY} != ${TARGET_FAMILY} ]]; then
-    libfakedir=${WI4MPI_LIBEXEC}/fakelib${FROM_FAMILY}/
-    [[ ! -d $libfakedir ]] && { echo "Error: could not find the wrapper extra libdir." >&2 ; exit 1; } 
-          export LD_LIBRARY_PATH=${libfakedir}:$LD_LIBRARY_PATH
-fi
-
-[[ -n "$VERBOSE" ]] && echo "C :export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
-
-#LANGUAGE="${LANGUAGE^^}"  # convert to uppercase
-#echo "Wrapping the calls from $FROM to $TARGET for the $LANGUAGE LANGUAGE."
-#case $LANGUAGE in
-#    C | C++ )
-#	libwi4mpi=${WI4MPI_LIBEXEC}/libwi4mpi_${FROM_FAMILY}_${TARGET_FAMILY}.so
-#	[[ ! -f $libwi4mpi ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; } 
-#	[[ ! -f ${TRUE_MPI_LIB} ]] && { echo "Error: could not find the target mpi library." >&2 ; exit 1; }
-#	
-#	export TRUE_MPI_F_LIB
-#   export TRUE_MPI_LIB
-#	export LD_PRELOAD="${LD_PRELOAD:+${LD_PRELOAD} }${libwi4mpi} ${TRUE_MPI_F_LIB} ${TRUE_MPI_LIB}"
-#
-#	if [[ -n "$VERBOSE" ]]; then
-#	    echo "export TRUE_MPI_F_LIB=${TRUE_MPI_F_LIB}"
-#	    echo "export TRUE_MPI_LIB=${TRUE_MPI_LIB}"
-#	    echo "export LD_PRELOAD=\"${LD_PRELOAD}\""
-#	fi
-#
-#	# replace the libmpi.so/libmpi.so.12 by an empty library from fakelib_${FROM_FAMILY}
-#	if [[ ${FROM_FAMILY} != ${TARGET_FAMILY} ]]; then
-#	    libfakedir=${WI4MPI_LIBEXEC}/fakelib${FROM_FAMILY}/
-#	    [[ ! -d $libfakedir ]] && { echo "Error: could not find the wrapper extra libdir." >&2 ; exit 1; } 
-#            export LD_LIBRARY_PATH=${libfakedir}:$LD_LIBRARY_PATH
-#	    [[ -n "$VERBOSE" ]] && echo "C :export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
-#	fi
-#	
-#   #
-#   if [[ $LANGUAGE == C++ ]]; then
-#      libfakedir_cxx=${WI4MPI_LIBEXEC}/fakelibCXX/
-#       [[ ! -d $libfakedir_cxx ]] && { echo "Error: could not find the wrapper extra libdircxx." >&2 ; exit 1; } 
-#            export LD_LIBRARY_PATH=${libfakedir_cxx}:$LD_LIBRARY_PATH
-#	    [[ -n "$VERBOSE" ]] && echo "C++ :export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
-#	fi
-#	;;
-#    FORTRAN )
-#    	libwi4mpi=${WI4MPI_LIBEXEC}/libwi4mpi_f_${FROM_FAMILY}_${TARGET_FAMILY}.so
-#
-#	[[ ! -f $libwi4mpi ]] && { echo "Error: could not find the wrapper." >&2 ; exit 1; }
-#	[[ ! -f ${TRUE_MPI_LIB} ]] && { echo "Error: could not find the target mpi library." >&2 ; exit 1; }
-#	[[ ! -f ${TRUE_MPI_FLIB} ]] && { echo "Error: could not find the target mpi fortran library." >&2 ; exit 1; }
-#
-#	export LD_PRELOAD="${LD_PRELOAD:+${LD_PRELOAD} }${libwi4mpi} ${TRUE_MPI_FLIB} ${TRUE_MPI_LIB}"
-#   
-#	# replace the libmpi_f77.so.1 && libmpi_f90.so.1/libmpifort.so.12 by an empty library from fakelib_${FROM_FAMILY}
-#	if [[ ${FROM_FAMILY} != ${TARGET_FAMILY} ]]; then
-#	    libfakedir=${WI4MPI_LIBEXEC}/fakelib${FROM_FAMILY}/
-#	    [[ ! -d $libfakedir ]] && { echo "Error: could not find the wrapper extra libdiri(FORTRAN)." >&2 ; exit 1; } 
-#            export LD_LIBRARY_PATH=${libfakedir}:$LD_LIBRARY_PATH
-#	    [[ -n "$VERBOSE" ]] && echo "FORTRAN :export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
-#	fi
-#
-#	if [[ -n "$VERBOSE" ]]; then
-#	    echo "export LD_PRELOAD=\"${LD_PRELOAD}\""
-#	fi
-#	;;
-#    *) echo "Error: Unsupported Language." >&2 ; exit 1 ;;
-#esac
-
-# Execute PROGRAM
 exec "$@"
